import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { useState } from "react";
import { BsSearch } from "react-icons/bs";




export default function Home() {
  const [city, setCity] = useState("");
  const [Weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);
  
 const ATM_KEY = "3b762aabb1ab28c97b70d949ba859ad4"
  const url = `https://api.openweathermap.org/data/2.5/weather?q=ibadan&units=imperial&appid=${ATM_KEY}`
  
 

  const fetchWeather = (e) => {
  e.preventDefault()
  setLoading(true)
  axios.get(url).then((response) => {
    setWeather(response.data)
    console.log(response.data);
  })
  setCity("");
  setLoading(false)
} 

  return (
    <div>
      <Head>
        <title>Weather-Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Image src="https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.wired.com%2Fstory%2Fextreme-weather-2022-just-getting-started%2F&psig=AOvVaw2mTycAlYlROBwmCBEnHa1p&ust=1666740070777000&source=images&cd=vfe&ved=0CA0QjRxqFwoTCMDD1OKA-voCFQAAAAAdAAAAABAF"
     layout='fill'
     />
    </div>
  )
}
